version: '3.1'

services:
  techjobusa-mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: techjobusa
    ports:
      - "3306:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - techjobusa-mysql-data:/var/lib/mysql


volumes:
  techjobusa-mysql-data:
  techjobusa-redis-data: